branches:
  only:
    - master
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - redis-server
install:
  - pip install .
  - pip install -r test_requirements.txt
  - pip install coveralls
script:
  - ./test_me.sh
after_success:
  - coveralls
