language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
#  - "3.6" Waiting for pylint to support python 3.6: https://github.com/postlund/pyatv/issues/18
install:
  - pip install .
  - pip install -r test_requirements.txt
script:
  - py.test --pylint --doctest-modules --pylint-error-types=WEF --cov=smserver smserver test
